{{ $labels := include "kommander-thanos.labels" . | indent 4  }}
{{- if .Values.thanos.query.enabled }}
{{- range .Values.thanos.query.serviceDiscoveryFileConfigMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
  labels:
{{ $labels }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
data:
  stores.yaml: |-
    - targets: []
{{- end}}
{{- end }}