
image:
  repository: "quay.io/external_storage/local-volume-provisioner"
  tag: "v2.3.2"
  pullPolicy: "IfNotPresent"

storageclass:
  - isDefault: true
    reclaimPolicy: delete
    volumeBindingMode: WaitForFirstConsumer
