{{- if .Values.grafana.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.mesosphereResources.hooks.prometheus.jobName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Values.mesosphereResources.hooks.prometheus.jobName }}
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.16.2
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - kubectl create configmap {{ .Values.mesosphereResources.hooks.prometheus.configmapName }} -n {{ .Release.Namespace }} -oyaml --from-literal=CLUSTER_ID=$(kubectl get namespace kube-system -o jsonpath="{.metadata.uid}")
      restartPolicy: OnFailure
{{- end }}
