---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-volume-provisioner-configmap
  namespace: kubeaddons
data:
  storageClassMap: |
    localvolumeprovisioner:
       hostDir: /mnt/disks
       mountDir: /mnt/disks
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: ext4
