---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localvolumeprovisioner
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageclass.isDefault | default "true" | quote }}
    kubernetes.io/description: Local volume provisioner StorageClass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode | default delete | quote }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy | default WaitForFirstConsumer | quote }}
{{- end }}
