dependencies:
- name: kubefed
  version: "0.1.0-rc6"
  repository: "https://raw.githubusercontent.com/kubernetes-sigs/kubefed/master/charts"
  condition: kubefed.enabled, global.kubefed.enabled
- name: kommander-cluster-lifecycle
  version: "0.1.5"
  repository: "https://mesosphere.github.io/kommander-cluster-lifecycle/charts"
  condition: kommander-cluster-lifecycle.enabled, global.kommander-cluster-lifecycle.enabled
- name: thanos
  version: 0.3.5
  repository: https://kubernetes-charts.banzaicloud.com
  condition: thanos.enabled
- name: grafana
  version: 3.8.*
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: grafana.enabled
- name: karma
  version: 1.1.*
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: karma.enabled
